<?php

namespace AppBundle\Repository;

/**
 * CatArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatArticlesRepository extends \Doctrine\ORM\EntityRepository
{
}
