<?php

namespace AppBundle\Repository;

/**
 * CatArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
